<?php
/**
 * Build fixed-palette Birds Theme packages and the local palette showcase CSS.
 *
 * Usage:
 *   php scripts/build-theme.php --all --version=0.4.0
 *   php scripts/build-theme.php --palette=mist-gray --version=0.4.0
 *   php scripts/build-theme.php --demo
 *   php scripts/build-theme.php --demo-package --version=0.4.0
 */

if ( PHP_SAPI !== 'cli' ) {
	exit( "This script must run from the command line.\n" );
}

$root = dirname( __DIR__ );
$json = $root . '/scripts/palettes.json';

if ( ! is_file( $json ) ) {
	exit( "Palette source is missing: {$json}\n" );
}

$presets = json_decode( file_get_contents( $json ), true );

if ( ! is_array( $presets ) || empty( $presets ) ) {
	exit( "Palette source is not valid JSON.\n" );
}

$style_source = file_get_contents( $root . '/style.css' );
$version       = '';

if ( preg_match( '/^Version:\s*(.+)$/m', $style_source, $matches ) ) {
	$version = trim( $matches[1] );
}

$options = array(
	'all'          => false,
	'demo'         => false,
	'demo_package' => false,
	'palette'      => '',
	'version'      => $version,
);

foreach ( array_slice( $argv, 1 ) as $argument ) {
	if ( '--all' === $argument ) {
		$options['all'] = true;
	} elseif ( '--demo' === $argument ) {
		$options['demo'] = true;
	} elseif ( '--demo-package' === $argument ) {
		$options['demo']         = true;
		$options['demo_package'] = true;
	} elseif ( 0 === strpos( $argument, '--palette=' ) ) {
		$options['palette'] = substr( $argument, 10 );
	} elseif ( 0 === strpos( $argument, '--version=' ) ) {
		$options['version'] = substr( $argument, 10 );
	}
}

if ( ! preg_match( '/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/', $options['version'] ) ) {
	exit( "Version must look like 0.4.0 or 0.4.0-rc1.\n" );
}

function birds_build_remove_tree( $path ) {
	if ( ! is_dir( $path ) ) {
		return;
	}

	$items = scandir( $path );

	foreach ( $items as $item ) {
		if ( '.' === $item || '..' === $item ) {
			continue;
		}

		$child = $path . '/' . $item;

		if ( is_dir( $child ) && ! is_link( $child ) ) {
			birds_build_remove_tree( $child );
		} else {
			unlink( $child );
		}
	}

	rmdir( $path );
}

function birds_build_copy_tree( $source, $destination, $excluded = array() ) {
	if ( ! is_dir( $destination ) && ! mkdir( $destination, 0755, true ) ) {
		throw new RuntimeException( "Cannot create {$destination}" );
	}

	$items = scandir( $source );

	foreach ( $items as $item ) {
		if ( '.' === $item || '..' === $item ) {
			continue;
		}
		if ( in_array( $item, $excluded, true ) ) {
			continue;
		}

		$from = $source . '/' . $item;
		$to   = $destination . '/' . $item;

		if ( is_dir( $from ) ) {
			birds_build_copy_tree( $from, $to );
		} elseif ( ! copy( $from, $to ) ) {
			throw new RuntimeException( "Cannot copy {$from}" );
		}
	}
}

function birds_build_apply_palette( $style, $variables ) {
	foreach ( $variables as $name => $value ) {
		$pattern = '/(^\s*' . preg_quote( $name, '/' ) . '\s*:\s*)[^;]+(;)/m';
		$count   = 0;
		$style   = preg_replace_callback(
			$pattern,
			static function ( $matches ) use ( $value ) {
				return $matches[1] . $value . $matches[2];
			},
			$style,
			-1,
			$count
		);

		if ( $count > 1 ) {
			throw new RuntimeException( "Palette variable {$name} matched more than once." );
		}
	}

	return $style;
}

function birds_build_write_demo_css( $root, $presets ) {
	$css  = "/* Generated from scripts/palettes.json. Do not edit this file directly. */\n";
	$css .= "\n";

	foreach ( $presets as $slug => $preset ) {
		$css .= 'body[data-palette="' . $slug . '"] {' . "\n";

		foreach ( $preset['variables'] as $name => $value ) {
			$css .= '  ' . $name . ': ' . $value . ';' . "\n";
		}

		$css .= "}\n\n";
	}

	$css .= "body[data-palette]:not([data-palette=\"classic\"]) {\n";
	$css .= "  background:\n";
	$css .= "    radial-gradient(circle at 8% 0%, var(--glow), transparent 34%),\n";
	$css .= "    radial-gradient(circle at 96% 58%, var(--glow-soft), transparent 40%),\n";
	$css .= "    repeating-conic-gradient(from 45deg, var(--texture) 0 25%, var(--texture-dark) 0 50%) 0 0 / 4px 4px,\n";
	$css .= "    var(--desktop);\n";
	$css .= "}\n\n";

	foreach ( $presets as $slug => $preset ) {
		$css .= 'html:has(body[data-palette="' . $slug . '"]) { background: var(--desktop); }' . "\n";
	}

	$targets = array(
		$root . '/prototype/palettes.css',
		$root . '/assets/demo/palettes.css',
	);

	if ( ! is_dir( $root . '/assets/demo' ) && ! mkdir( $root . '/assets/demo', 0755, true ) ) {
		throw new RuntimeException( 'Cannot create assets/demo' );
	}

	foreach ( $targets as $target ) {
		if ( false === file_put_contents( $target, $css ) ) {
			throw new RuntimeException( "Cannot write {$target}" );
		}
	}
}

try {
	if ( $options['demo'] || $options['all'] || '' !== $options['palette'] ) {
		birds_build_write_demo_css( $root, $presets );
	}

	if ( ! $options['all'] && '' === $options['palette'] && ! $options['demo_package'] ) {
		echo "Wrote prototype/palettes.css\n";
		exit( 0 );
	}

	$selected = $options['demo_package'] ? array( 'classic' ) : ( $options['all'] ? array_keys( $presets ) : array( $options['palette'] ) );

	foreach ( $selected as $slug ) {
		if ( ! isset( $presets[ $slug ] ) ) {
			throw new InvalidArgumentException( "Unknown palette: {$slug}" );
		}

		$preset      = $presets[ $slug ];
		$package_slug = $options['demo_package'] ? 'birds-demo' : 'birds-' . $slug;
		$package_dir = $root . '/build/' . $package_slug . '-' . $options['version'];
		$zip_path    = $root . '/build/' . $package_slug . '-' . $options['version'] . '.zip';
		$theme_dir   = $package_dir . '/' . $package_slug;

		birds_build_remove_tree( $package_dir );
		if ( is_file( $zip_path ) ) {
			unlink( $zip_path );
		}

		mkdir( $theme_dir, 0755, true );

		$root_files = array(
			'404.php',
			'archive.php',
			'author.php',
			'comments.php',
			'footer.php',
			'front-page.php',
			'functions.php',
			'header.php',
			'home.php',
			'index.php',
			'LICENSE',
			'page.php',
			'readme.txt',
			'search.php',
			'single.php',
			'style.css',
			'theme.json',
		);

		foreach ( $root_files as $file ) {
			$source = $root . '/' . $file;
			$target = $theme_dir . '/' . $file;

			if ( ! is_file( $source ) || ! copy( $source, $target ) ) {
				throw new RuntimeException( "Cannot package {$file}" );
			}
		}

		$directories = array(
			'assets'          => $options['demo_package'] ? array() : array( 'demo' ),
			'inc'             => $options['demo_package'] ? array() : array( 'demo-palette.php' ),
			'languages'       => array(),
			'template-parts'  => array(),
		);

		foreach ( $directories as $directory => $excluded ) {
			birds_build_copy_tree( $root . '/' . $directory, $theme_dir . '/' . $directory, $excluded );
		}

		$package_style = file_get_contents( $theme_dir . '/style.css' );
		$package_style = birds_build_apply_palette( $package_style, $preset['variables'] );
		$package_style = preg_replace( '/^Version:\s*.+$/m', 'Version: ' . $options['version'], $package_style );
		$theme_name    = ( 'classic' === $slug || $options['demo_package'] ) ? 'Birds' : 'Birds — ' . $preset['label'];
		$package_style = preg_replace( '/^Theme Name:\s*.+$/m', 'Theme Name: ' . $theme_name, $package_style );
		file_put_contents( $theme_dir . '/style.css', $package_style );

		$package_functions = file_get_contents( $theme_dir . '/functions.php' );
		$package_functions = preg_replace( "/define\( 'BIRDS_VERSION', '[^']+' \);/", "define( 'BIRDS_VERSION', '{$options['version']}' );", $package_functions );
		file_put_contents( $theme_dir . '/functions.php', $package_functions );

		$package_readme = file_get_contents( $theme_dir . '/readme.txt' );
		$package_readme = preg_replace( '/^Stable tag:\s*.+$/m', 'Stable tag: ' . $options['version'], $package_readme );
		file_put_contents( $theme_dir . '/readme.txt', $package_readme );

		if ( ! class_exists( 'ZipArchive' ) ) {
			throw new RuntimeException( 'PHP ZipArchive is required to create release archives.' );
		}

		$zip = new ZipArchive();
		if ( true !== $zip->open( $zip_path, ZipArchive::CREATE ) ) {
			throw new RuntimeException( "Cannot create {$zip_path}" );
		}

		$iterator = new RecursiveIteratorIterator(
			new RecursiveDirectoryIterator( $package_dir, FilesystemIterator::SKIP_DOTS ),
			RecursiveIteratorIterator::SELF_FIRST
		);

		foreach ( $iterator as $file_info ) {
			$absolute = $file_info->getPathname();
			$relative = substr( $absolute, strlen( $package_dir ) + 1 );

			if ( $file_info->isDir() ) {
				$zip->addEmptyDir( $relative );
			} else {
				$zip->addFile( $absolute, $relative );
			}
		}

		$zip->close();
		echo "Built {$zip_path}\n";
	}
} catch ( Throwable $error ) {
	fwrite( STDERR, $error->getMessage() . "\n" );
	exit( 1 );
}
